# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

  # 1. Installer la version du SDK .NET requise
- task: UseDotNet@2
  displayName: 'Installer .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'   # Exemple : version 6 du SDK .NET

# 5. Générer un fichier d’information sur la build
- script: |
    echo "Pipeline: $(Build.DefinitionName)" > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
    echo "Build ID: $(Build.BuildId)" >> Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
    echo "Build Number: $(Build.BuildNumber)" >> Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
  displayName: 'Écrire les infos de build'



